# Generated by Django 2.2.6 on 2019-10-25 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('img', models.ImageField(upload_to='items')),
                ('body', models.TextField(db_index=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag', models.ManyToManyField(related_name='items', to='product.Tag')),
            ],
        ),
    ]
